### ISSUE TITLE
test.data=null fails

### ISSUE THREAD

**Issue by zhangl861** [beechung/Latent-Factor-Models#6]
> ans = fit.bst(obs.train=obs.train, x.obs.train=x.obs.train, x_src=x_src, x_dst=x_dst, x_ctx=x_ctx,out.dir = "/tmp/unit-test/simulated-mtx-uvw-10K", model.name="uvw", nFactors=3, nIter=10);

WARNING: You did not specify the following components in factor: gamma

WARNING: You did not specify the following components in param: h0, var_gamma

================= START fit.MCEM =====================================
 Initial loglik: CD =  -19358.42494, E =            NA (0.01 sec)
Error in data.frame(Method = "MCEM", Iter = iter, nSteps = nSamples, CDlogL = loglik,  :
  arguments imply differing number of rows: 1, 0

**Comment by FunData7** [comment]
I get the same error with very last commit. How to deal with that? Could you please help? Thanks a lot!
